import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Download, FileText, Table, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface ExportMenuProps {
  analysis: {
    title: string;
    summary: string;
    insights: any[];
    charts: any[];
  };
  data?: { headers: string[]; rows: any[] };
}

export function ExportMenu({ analysis, data }: ExportMenuProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const exportCSV = () => {
    if (!data) {
      toast({ title: "No data available", variant: "destructive" });
      return;
    }

    const csvContent = [
      data.headers.join(","),
      ...data.rows.map((row) =>
        data.headers
          .map((h) => {
            const val = row[h];
            if (typeof val === "string" && (val.includes(",") || val.includes('"'))) {
              return `"${val.replace(/"/g, '""')}"`;
            }
            return val ?? "";
          })
          .join(",")
      ),
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${analysis.title.replace(/[^a-zA-Z0-9]/g, "_")}.csv`;
    link.click();
    URL.revokeObjectURL(url);

    toast({ title: "CSV exported" });
  };

  const exportReport = () => {
    setIsExporting(true);

    const insightsText = analysis.insights
      .map((i, idx) => {
        const text = typeof i === "string" ? i : i.insight;
        return `${idx + 1}. ${text}`;
      })
      .join("\n");

    const chartsText = analysis.charts
      .map((c, idx) => `${idx + 1}. ${c.title} (${c.type})`)
      .join("\n");

    const report = `
DATA ANALYSIS REPORT
====================

Title: ${analysis.title}
Date: ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}

Summary
-------
${analysis.summary}

Key Insights
------------
${insightsText}

Charts
------
${chartsText}

---
Generated by Noema
    `.trim();

    const blob = new Blob([report], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${analysis.title.replace(/[^a-zA-Z0-9]/g, "_")}_Report.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setIsExporting(false);
    toast({ title: "Report exported" });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" data-testid="button-export">
          {isExporting ? (
            <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
          ) : (
            <Download className="w-3.5 h-3.5 mr-1.5" />
          )}
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportReport} data-testid="export-report">
          <FileText className="w-3.5 h-3.5 mr-2" />
          Report (.txt)
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={exportCSV} disabled={!data} data-testid="export-csv">
          <Table className="w-3.5 h-3.5 mr-2" />
          Data (.csv)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
